In [5]:
import pandas as pd

In [ ]:
class Node:
    ''' node class '''
    def __init__(self,data=[]):
        self.data = data
        self.next = None

In [3]:
class  LinkedList:
    '''docstring for  LinkedList.'''

    def __init__(self):
        self.head = None
        self.size = 0

    def size(self):
        ''' o(1): simple returns attribute '''
        return self.size

    def calculate_size(self):
        ''' O(n): travers all item and calculate size again'''
        start = self.head
        size = 0
        while  start:
            size =+ 1
            start = start.next
        self.size = size
        return size

    def insertStart(self,data):
        '''O(1): insert item at start(head) '''
        self.size += 1
        new_node = Node(data)
        if not self.head:
            self.head = new_node
        else:
            new_node.next = self.head


    def get_last_node(self):
        '''O(n): returns the last item of linked list'''
        start = self.head
        while start.next:
            start = start.next
        return start

    def insertLast(self,data):
        ''' O(n): insert node at last '''
        new_node = Node(data)
        if self.head is None:
            self.head = new_node
        self.size =+ 1
        last_node = self.get_last_node()
        last_node.next = new_node

    def search_data(self,data):
        ''' O(n): return the first matched node unless -1'''
        start = self.head
        while  start.data != data and start.next:
            start = start.next
        return start if start.data == data else -1

    def traverse(self):
        '''O(n): print each node '''
        start = self.head
        while start.next:
            start = start.next
            print(start, '>>>>>',start.data)

    def remove(self,data):
        '''' O(n):  search node by data and remove that by returnin gnode object '''
        if self.head is None:
            return None
        first = second = self.head
        while second.data != data and first.next:
            second = first.next
            start = start.next
            if second.data == data:
                break
        if first.next is None:
            return None
        first.next = second.next
        return second

In [44]:
''' createing a linked list of 1000  node '''
def get_hash_data(num):
    return num**2

ll = LinkedList()

for i in range(10):
    data = get_hash_data(i)
    ll.insertStart(data)
ll.traverse()

In [45]:
print(ll.size)
ll.traverse()

10

In [39]:
ll.insertStart(5)

In [16]:
data = pd.read_csv('diamond.csv')

In [20]:
data[]

,id,diamond_clarity,diamond_color,diamond_shape,carat_start,carat_end,factor
0,2,SI,IJ,Round,0.05,0.09,9.90
1,4,SI,IJ,Round,0.15,0.19,10.85
2,5,SI,IJ,Round,0.20,0.24,15.84
3,6,SI1,I,Round,0.25,0.29,15.84
4,7,SI1,J,Round,0.25,0.29,15.84
...,...,...,...,...,...,...,...
2675,2518,VS2,J,Pear,5.00,5.99,160.00
2676,2536,IF,L,Pear,5.00,5.99,115.00
2677,2553,SI2,M,Pear,5.00,5.99,63.00
2678,2572,VS1,E,Pear,10.00,10.99,870.00
2679,2590,I3,F,Pear,10.00,10.99,21.00